version: "3"
services:
  app:
    image: juliusfreudenberger/distributed-systems:latest
    container_name: distributed-systems-app
    build: .
    ports:
      - "127.0.0.1:8090:8090"

  db:
    image: postgres
    container_name: distributed-systems-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "127.0.0.1:5432:5432"